# Generated by Django 2.2.7 on 2019-11-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='mobile',
        ),
    ]
